// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/task/task.proto

package task

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Assignee             string   `protobuf:"bytes,5,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Deadline             string   `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Done                 bool     `protobuf:"varint,8,opt,name=done,proto3" json:"done,omitempty"`
	Overdue              bool     `protobuf:"varint,9,opt,name=overdue,proto3" json:"overdue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Task) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Task) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Task) GetAssignee() string {
	if m != nil {
		return m.Assignee
	}
	return ""
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *Task) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Task) GetOverdue() bool {
	if m != nil {
		return m.Overdue
	}
	return false
}

type MakeDoneRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeDoneRequest) Reset()         { *m = MakeDoneRequest{} }
func (m *MakeDoneRequest) String() string { return proto.CompactTextString(m) }
func (*MakeDoneRequest) ProtoMessage()    {}
func (*MakeDoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{1}
}

func (m *MakeDoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeDoneRequest.Unmarshal(m, b)
}
func (m *MakeDoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeDoneRequest.Marshal(b, m, deterministic)
}
func (m *MakeDoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeDoneRequest.Merge(m, src)
}
func (m *MakeDoneRequest) XXX_Size() int {
	return xxx_messageInfo_MakeDoneRequest.Size(m)
}
func (m *MakeDoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeDoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeDoneRequest proto.InternalMessageInfo

func (m *MakeDoneRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MakeLateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeLateRequest) Reset()         { *m = MakeLateRequest{} }
func (m *MakeLateRequest) String() string { return proto.CompactTextString(m) }
func (*MakeLateRequest) ProtoMessage()    {}
func (*MakeLateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{2}
}

func (m *MakeLateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeLateRequest.Unmarshal(m, b)
}
func (m *MakeLateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeLateRequest.Marshal(b, m, deterministic)
}
func (m *MakeLateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeLateRequest.Merge(m, src)
}
func (m *MakeLateRequest) XXX_Size() int {
	return xxx_messageInfo_MakeLateRequest.Size(m)
}
func (m *MakeLateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeLateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeLateRequest proto.InternalMessageInfo

type UpdateTaskRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Task                 *Task    `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{3}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{4}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{5}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type GetAllResponse struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{6}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type FlagResponse struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlagResponse) Reset()         { *m = FlagResponse{} }
func (m *FlagResponse) String() string { return proto.CompactTextString(m) }
func (*FlagResponse) ProtoMessage()    {}
func (*FlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{7}
}

func (m *FlagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlagResponse.Unmarshal(m, b)
}
func (m *FlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlagResponse.Marshal(b, m, deterministic)
}
func (m *FlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlagResponse.Merge(m, src)
}
func (m *FlagResponse) XXX_Size() int {
	return xxx_messageInfo_FlagResponse.Size(m)
}
func (m *FlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlagResponse proto.InternalMessageInfo

func (m *FlagResponse) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func init() {
	proto.RegisterType((*Task)(nil), "task.Task")
	proto.RegisterType((*MakeDoneRequest)(nil), "task.MakeDoneRequest")
	proto.RegisterType((*MakeLateRequest)(nil), "task.MakeLateRequest")
	proto.RegisterType((*UpdateTaskRequest)(nil), "task.UpdateTaskRequest")
	proto.RegisterType((*DeleteTaskRequest)(nil), "task.DeleteTaskRequest")
	proto.RegisterType((*GetAllRequest)(nil), "task.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "task.GetAllResponse")
	proto.RegisterType((*FlagResponse)(nil), "task.FlagResponse")
}

func init() { proto.RegisterFile("proto/task/task.proto", fileDescriptor_152e577c5c92a6d4) }

var fileDescriptor_152e577c5c92a6d4 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x25, 0xd9, 0x74, 0x37, 0x9d, 0x85, 0x5d, 0x75, 0xd8, 0x15, 0x56, 0x25, 0x50, 0x30, 0x97,
	0x3d, 0x15, 0xa9, 0x1c, 0x90, 0xe0, 0x54, 0xed, 0x0a, 0x2e, 0x70, 0x09, 0x70, 0x46, 0xa6, 0x1e,
	0xa2, 0xa8, 0x51, 0x52, 0x62, 0xb7, 0xff, 0xcc, 0x89, 0x5f, 0x40, 0x1e, 0xc7, 0x6d, 0xda, 0x12,
	0x2e, 0xd1, 0xcc, 0x7b, 0xf3, 0x66, 0x3c, 0xcf, 0x0e, 0xdc, 0xae, 0xdb, 0xc6, 0x36, 0xaf, 0xad,
	0x32, 0x2b, 0xfe, 0xcc, 0x38, 0xc7, 0xc4, 0xc5, 0xf2, 0x4f, 0x04, 0xc9, 0x57, 0x65, 0x56, 0x78,
	0x05, 0x71, 0xa9, 0x45, 0x94, 0x45, 0x77, 0xe3, 0x3c, 0x2e, 0x35, 0x3e, 0x07, 0x58, 0xb6, 0xa4,
	0x2c, 0xe9, 0xef, 0xca, 0x8a, 0x98, 0xf1, 0x71, 0x87, 0x2c, 0xac, 0xa3, 0x37, 0x6b, 0x1d, 0xe8,
	0x33, 0x4f, 0x77, 0x88, 0xa7, 0x35, 0x55, 0xd4, 0xd1, 0x89, 0xa7, 0x3b, 0x64, 0x61, 0x71, 0x0a,
	0xa9, 0x32, 0xa6, 0x2c, 0x6a, 0x22, 0x31, 0x62, 0x72, 0x97, 0xe3, 0x0d, 0x8c, 0x6c, 0x69, 0x2b,
	0x12, 0xe7, 0x4c, 0xf8, 0xc4, 0x29, 0x34, 0x29, 0x5d, 0x95, 0x35, 0x89, 0x0b, 0xaf, 0x08, 0x39,
	0x22, 0x24, 0xba, 0xa9, 0x49, 0xa4, 0x59, 0x74, 0x97, 0xe6, 0x1c, 0xa3, 0x80, 0x8b, 0x66, 0x4b,
	0xad, 0xde, 0x90, 0x18, 0x33, 0x1c, 0x52, 0xf9, 0x12, 0xae, 0x3f, 0xab, 0x15, 0x3d, 0x34, 0x35,
	0xe5, 0xf4, 0x6b, 0x43, 0xc6, 0xf6, 0x76, 0x4f, 0xdc, 0xee, 0x72, 0xe2, 0x4b, 0x3e, 0x29, 0x1b,
	0x4a, 0xe4, 0x3d, 0x4c, 0xbe, 0xf1, 0x76, 0xce, 0xac, 0x01, 0x1d, 0xbe, 0x00, 0x36, 0x95, 0xdd,
	0xba, 0x9c, 0xc3, 0x8c, 0xdd, 0x66, 0x81, 0x37, 0xfb, 0x15, 0x4c, 0x1e, 0xd8, 0x83, 0xff, 0x34,
	0x91, 0xd7, 0xf0, 0xe4, 0x23, 0xd9, 0x45, 0x55, 0x85, 0xd1, 0x73, 0xb8, 0x0a, 0x80, 0x59, 0x37,
	0xb5, 0x21, 0xcc, 0x60, 0xe4, 0xfa, 0x19, 0x11, 0x65, 0x67, 0x47, 0x83, 0x3c, 0x21, 0x25, 0x3c,
	0xfe, 0x50, 0xa9, 0x62, 0xa7, 0x40, 0x48, 0x7e, 0x56, 0xaa, 0xe0, 0x31, 0x69, 0xce, 0xf1, 0xfc,
	0x77, 0xec, 0xd6, 0xac, 0x55, 0x51, 0xd6, 0xc5, 0x17, 0x6a, 0xb7, 0xe5, 0x92, 0x70, 0x06, 0x70,
	0xcf, 0x77, 0xcc, 0x6f, 0xa2, 0xd7, 0x78, 0x8a, 0x3e, 0xee, 0x77, 0x95, 0x8f, 0xf0, 0x3d, 0xc0,
	0xde, 0x16, 0x7c, 0xe6, 0x6b, 0x4e, 0x8c, 0x1a, 0x10, 0xbf, 0x85, 0x34, 0xdc, 0x04, 0xde, 0xfa,
	0x8a, 0xa3, 0x9b, 0x19, 0x9e, 0xba, 0xf7, 0x31, 0x4c, 0x3d, 0x71, 0x76, 0x40, 0xfc, 0x0e, 0x2e,
	0xbd, 0x9d, 0xae, 0xd4, 0xe0, 0x53, 0x5f, 0x74, 0x60, 0xf9, 0xf4, 0xe6, 0x10, 0x3c, 0x3e, 0xb1,
	0x7b, 0x18, 0xfd, 0x13, 0xf7, 0x1e, 0xca, 0xbf, 0x87, 0xfe, 0x38, 0xe7, 0x7f, 0xee, 0xcd, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xe8, 0xf1, 0x70, 0x8c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagingServiceClient is the client API for ManagingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagingServiceClient interface {
	CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*FlagResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error)
	MakeDone(ctx context.Context, in *MakeDoneRequest, opts ...grpc.CallOption) (*FlagResponse, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error)
	GetAllTasks(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	MakeLate(ctx context.Context, in *MakeLateRequest, opts ...grpc.CallOption) (*FlagResponse, error)
}

type managingServiceClient struct {
	cc *grpc.ClientConn
}

func NewManagingServiceClient(cc *grpc.ClientConn) ManagingServiceClient {
	return &managingServiceClient{cc}
}

func (c *managingServiceClient) CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) MakeDone(ctx context.Context, in *MakeDoneRequest, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/MakeDone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) GetAllTasks(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/GetAllTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managingServiceClient) MakeLate(ctx context.Context, in *MakeLateRequest, opts ...grpc.CallOption) (*FlagResponse, error) {
	out := new(FlagResponse)
	err := c.cc.Invoke(ctx, "/task.ManagingService/MakeLate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagingServiceServer is the server API for ManagingService service.
type ManagingServiceServer interface {
	CreateTask(context.Context, *Task) (*FlagResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*FlagResponse, error)
	MakeDone(context.Context, *MakeDoneRequest) (*FlagResponse, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*FlagResponse, error)
	GetAllTasks(context.Context, *GetAllRequest) (*GetAllResponse, error)
	MakeLate(context.Context, *MakeLateRequest) (*FlagResponse, error)
}

// UnimplementedManagingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedManagingServiceServer struct {
}

func (*UnimplementedManagingServiceServer) CreateTask(ctx context.Context, req *Task) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedManagingServiceServer) UpdateTask(ctx context.Context, req *UpdateTaskRequest) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (*UnimplementedManagingServiceServer) MakeDone(ctx context.Context, req *MakeDoneRequest) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeDone not implemented")
}
func (*UnimplementedManagingServiceServer) DeleteTask(ctx context.Context, req *DeleteTaskRequest) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (*UnimplementedManagingServiceServer) GetAllTasks(ctx context.Context, req *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTasks not implemented")
}
func (*UnimplementedManagingServiceServer) MakeLate(ctx context.Context, req *MakeLateRequest) (*FlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeLate not implemented")
}

func RegisterManagingServiceServer(s *grpc.Server, srv ManagingServiceServer) {
	s.RegisterService(&_ManagingService_serviceDesc, srv)
}

func _ManagingService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).CreateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_MakeDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).MakeDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/MakeDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).MakeDone(ctx, req.(*MakeDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_GetAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).GetAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/GetAllTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).GetAllTasks(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagingService_MakeLate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeLateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagingServiceServer).MakeLate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.ManagingService/MakeLate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagingServiceServer).MakeLate(ctx, req.(*MakeLateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task.ManagingService",
	HandlerType: (*ManagingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _ManagingService_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _ManagingService_UpdateTask_Handler,
		},
		{
			MethodName: "MakeDone",
			Handler:    _ManagingService_MakeDone_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _ManagingService_DeleteTask_Handler,
		},
		{
			MethodName: "GetAllTasks",
			Handler:    _ManagingService_GetAllTasks_Handler,
		},
		{
			MethodName: "MakeLate",
			Handler:    _ManagingService_MakeLate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/task/task.proto",
}
